### ISSUE TITLE
ルーム詳細画面、最大延長時間を過ぎたときの挙動について

### ISSUE THREAD

**Issue by k0101-gitkraken** [18jn02-8/telledge#293]
ルーム詳細画面の最低通話時間終了後、最大延長時間に移行するがそれも終わった際の挙動が、講師生徒どちらも違いどちらもおかしい、具体的には、
[生徒]最大延長時間を超えると、－にタイマーが刻まれていく、通話は終了しない。
[講師]最大延長時間を超えると、タイマーがストップし、通話終了ボタン、経過時間、要望が隠れる、ただし通話した生徒がルーム待ち一覧には表示され、キャンセルできなくなる、また生徒名、SkypeIDが消えない。

**Comment by Tatsuki5274** [comment]
#302 と #303 にて対応済み
