### ISSUE TITLE
レビュー送信時、エラーが発生する

### ISSUE THREAD

**Issue by Tatsuki5274** [18jn02-8/telledge#298]
生徒が通話終了時、レビューを投稿するとSystem.InvalidOperationExceptionが表示される問題。
beginTimeがnullだったため開始時の処理に問題あり。

**Comment by Tatsuki5274** [comment]
#300 にて恐らく修正。
修正確認後、close。

**Comment by k0101-gitkraken** [comment]
今のところ自分の環境は問題なし、どのような時にエラーが出る？
